{
 "title": "gpu",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "pod GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL{pod!=''}", "legendFormat": "{{pod}} GPU {{gpu}}" }
   ]
  },
  {
   "title": "pod GPU Memory Usage Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{pod!=''}/(DCGM_FI_DEV_FB_USED{pod!=''} + DCGM_FI_DEV_FB_FREE{pod!=''})",
     "legendFormat": "{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, gpu) (DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, gpu) (DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE))",
     "legendFormat": "{{instance}}: gpu {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_TEMP", "legendFormat": "{{instance}}:gpu {{gpu}}" }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "DCGM_FI_DEV_POWER_USAGE", "legendFormat": "{{instance}} GPU {{gpu}}" }
   ]
  }
 ]
}