{
 "title": "pod-info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "Pod", "query": "-" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"kubelet\", container=\"\",image='',pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", container=\"\",image='',pod=~\".*$pod.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=~\".*$pod.*\"}",
     "legendFormat": "{{instance}},{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "pod GPU Memory Usage Util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{pod=~'.*$pod.*'}/(DCGM_FI_DEV_FB_USED{pod=~'.*$pod.*'} + DCGM_FI_DEV_FB_FREE{pod=~'.*$pod.*'})",
     "legendFormat": "{{instance}},{{pod}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "pod NPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_utilization{pod_name=~\".*$pod.*\"}",
     "legendFormat": "{{namespace}} {{pod_name}} {{model_name}} {{id}}"
    }
   ]
  },
  {
   "title": "pod NPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "npu_chip_info_used_memory{pod_name=~'.*$pod.*'}",
     "legendFormat": "{{namespace}} {{pod_name}} {{model_name}} {{id}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{job=\"kubelet\",pod=~\".*$pod.*\"}[2m]))",
     "legendFormat": "{{pod}} receive"
    },
    {
     "expr": "- sum by (pod) (rate(container_network_transmit_bytes_total{job=\"kubelet\",pod=~\".*$pod.*\"}[2m]))",
     "legendFormat": "{{pod}} send"
    }
   ]
  }
 ]
}